blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature request
    url: https://github.com/veechs/Bagshui/discussions/categories/ideas?discussions_q=
    about: Suggest an idea
  - name: ğŸ“• Documentation
    url: https://github.com/veechs/Bagshui/wiki
    about: FAQ, walkthroghs, and more
  - name: â“ Help
    url: https://github.com/veechs/Bagshui/discussions/categories/q-a?discussions_q=
    about: Ask a question